version: '3.1'
services:
  # api:
    # build: .
    # ports:
      # - "8080:8080"
    # links:
      # - db

  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "gamelog"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080